# Generated by Django 5.0.7 on 2024-10-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='qr code is aumatically generated just leave it as it is', upload_to='qr_codes'),
        ),
    ]
