# Generated by Django 5.0.7 on 2024-09-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_whatsappnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappnumber',
            name='whatsapp_verify_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
