# Generated by Django 5.0.7 on 2024-09-14 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='funnel_stage',
            field=models.CharField(choices=[('awareness', 'awareness'), ('interest', 'interest'), ('decision', 'decision'), ('purchase', 'purchase'), ('active', 'active'), ('dormant', 'dormant')], default='awareness', max_length=50),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conversations', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='sender',
            field=models.CharField(choices=[('customer', 'customer'), ('AI', 'AI')], max_length=50),
        ),
    ]
