# Generated by Django 5.0.7 on 2024-09-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_funnel_stage_alter_conversation_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_talked',
            field=models.DateField(auto_now=True),
        ),
    ]
