# Generated by Django 5.0.7 on 2024-09-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_last_talked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_talked',
            field=models.DateField(blank=True, null=True),
        ),
    ]
