# Generated by Django 5.0.7 on 2024-09-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_last_talked'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
