# Generated by Django 5.0.7 on 2024-09-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalation',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
